version: "2"
services:
  web:
    build: .
    links:
      - db
      - mail
      - redis
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: infra
      MYSQL_DATABASE: infra
      MYSQL_USER: infra
      MYSQL_PASSWORD: infra
      MYSQL_HOST: ""
    ports:
      - "3306:3306"

  nodejs:
    build: ./docker/nodejs
    volumes:
      - ./:/app

  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  redis:
    image: redis:3
